/**
 * payroll.test.js — zero-dependency regression suite.
 *
 * Run: node lib/payroll.test.js
 *
 * Every expected value in the FULL PAYSLIP section must be computed by hand
 * by a CPA before it is written here. A test that was generated by the code
 * it tests proves nothing. Where a value has not yet been hand-verified it is
 * marked PENDING-VERIFY and the suite says so at the end.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  toCentavos,
  toPesos,
  sssMSC,
  sssEmployee,
  philhealthEmployee,
  pagibigEmployee,
  withholdingTax,
  computePayroll,
  grossFromNet,
  compare,
} from './payroll.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rates = JSON.parse(readFileSync(join(__dirname, '..', 'rates', '2026.json'), 'utf8'));

/* ------------------------------------------------------------------ */

let passed = 0;
let failed = 0;
let pendingVerify = 0;
const failures = [];

function eq(actual, expected, label) {
  if (actual === expected) {
    passed++;
  } else {
    failed++;
    failures.push(`${label}\n    expected: ${expected}\n    actual:   ${actual}`);
  }
}

/** Truth assertion, for comparisons rather than exact values. */
function ok(condition, label) {
  eq(Boolean(condition), true, label);
}

/** Money equality, to the centavo. */
function peso(actual, expected, label) {
  eq(Math.round(actual * 100), Math.round(expected * 100), label);
}

/** Marks a value that still needs a CPA's hand-check against a real payslip. */
function pesoPending(actual, expected, label) {
  pendingVerify++;
  peso(actual, expected, label + '  [PENDING-VERIFY]');
}

function throws(fn, label) {
  try {
    fn();
    failed++;
    failures.push(`${label}\n    expected a throw, got none`);
  } catch {
    passed++;
  }
}

function section(name) {
  process.stdout.write(`\n  ${name}\n`);
}

/* ================================================================== */
section('Money helpers');

eq(toCentavos(0), 0, 'toCentavos(0)');
eq(toCentavos(1), 100, 'toCentavos(1)');
eq(toCentavos(25000), 2500000, 'toCentavos(25000)');
eq(toCentavos(0.1), 10, 'toCentavos(0.1)');
eq(toCentavos(1.005), 101, 'toCentavos(1.005) rounds half-up, not 100');
eq(toCentavos(313.795), 31380, 'toCentavos(313.795) half-up');
eq(toPesos(2500000), 25000, 'toPesos(2500000)');
eq(toPesos(31380), 313.8, 'toPesos(31380)');
throws(() => toCentavos(NaN), 'toCentavos(NaN) throws');
throws(() => toCentavos(Infinity), 'toCentavos(Infinity) throws');

/* ================================================================== */
section('SSS — monthly salary credit is STEPPED, not proportional');

peso(toPesos(sssMSC(toCentavos(25000), rates)), 25000, 'MSC of exactly 25,000');
peso(toPesos(sssMSC(toCentavos(25300), rates)), 25500, 'MSC of 25,300 steps UP to 25,500');
peso(toPesos(sssMSC(toCentavos(25100), rates)), 25000, 'MSC of 25,100 steps DOWN to 25,000');
peso(toPesos(sssMSC(toCentavos(1), rates)), 5000, 'MSC floors at 5,000');
peso(toPesos(sssMSC(toCentavos(4999), rates)), 5000, 'MSC floors at 5,000 just below');
peso(toPesos(sssMSC(toCentavos(35000), rates)), 35000, 'MSC at the cap');
peso(toPesos(sssMSC(toCentavos(200000), rates)), 35000, 'MSC caps at 35,000');
peso(toPesos(sssMSC(toCentavos(34999), rates)), 35000, 'MSC just below the cap');

peso(toPesos(sssEmployee(toCentavos(25000), rates)), 1250, 'SSS employee share at 25,000');
peso(toPesos(sssEmployee(toCentavos(50000), rates)), 1750, 'SSS employee share caps at 1,750');
peso(toPesos(sssEmployee(toCentavos(1000000), rates)), 1750, 'SSS share still caps at 1,750');
peso(toPesos(sssEmployee(toCentavos(25300), rates)), 1275,
  'SSS at 25,300 uses the 25,500 step, NOT 5% of 25,300');

/* ================================================================== */
section('PhilHealth — continuous, with a floor and a ceiling');

peso(toPesos(philhealthEmployee(toCentavos(25000), rates)), 625, 'PhilHealth at 25,000');
peso(toPesos(philhealthEmployee(toCentavos(10000), rates)), 250, 'PhilHealth exactly at the floor');
peso(toPesos(philhealthEmployee(toCentavos(8000), rates)), 250, 'PhilHealth below floor uses floor');
peso(toPesos(philhealthEmployee(toCentavos(1), rates)), 250, 'PhilHealth at 1 peso uses floor');
peso(toPesos(philhealthEmployee(toCentavos(100000), rates)), 2500, 'PhilHealth exactly at the ceiling');
peso(toPesos(philhealthEmployee(toCentavos(120000), rates)), 2500, 'PhilHealth above ceiling caps');
peso(toPesos(philhealthEmployee(toCentavos(10001), rates)), 250.03, 'PhilHealth one peso above floor');

/* ================================================================== */
section('Pag-IBIG — two rates, one cap');

peso(toPesos(pagibigEmployee(toCentavos(25000), rates)), 200, 'Pag-IBIG caps at 200');
peso(toPesos(pagibigEmployee(toCentavos(10000), rates)), 200, 'Pag-IBIG exactly at the salary cap');
peso(toPesos(pagibigEmployee(toCentavos(9000), rates)), 180, 'Pag-IBIG below the cap is 2%');
peso(toPesos(pagibigEmployee(toCentavos(1500), rates)), 15, 'Pag-IBIG at 1,500 uses the 1% rate');
peso(toPesos(pagibigEmployee(toCentavos(1400), rates)), 14, 'Pag-IBIG below 1,500 uses the 1% rate');
peso(toPesos(pagibigEmployee(toCentavos(1501), rates)), 30.02, 'Pag-IBIG just above 1,500 uses 2%');

/* ================================================================== */
section('Withholding — BIR published period brackets');

peso(toPesos(withholdingTax(toCentavos(20833), 'monthly', rates)), 0,
  'monthly: exactly at the exempt ceiling is still zero');
peso(toPesos(withholdingTax(toCentavos(20834), 'monthly', rates)), 0.15,
  'monthly: one peso into bracket 2');
peso(toPesos(withholdingTax(toCentavos(22925), 'monthly', rates)), 313.8,
  'monthly: the 25,000-salary case');
peso(toPesos(withholdingTax(toCentavos(33333), 'monthly', rates)), 1875,
  'monthly: top of bracket 2 equals the base of bracket 3');
peso(toPesos(withholdingTax(toCentavos(33334), 'monthly', rates)), 1875.2,
  'monthly: one peso into bracket 3');
peso(toPesos(withholdingTax(toCentavos(66667), 'monthly', rates)), 8541.8,
  'monthly: top of bracket 3 equals the base of bracket 4');
peso(toPesos(withholdingTax(toCentavos(166667), 'monthly', rates)), 33541.8,
  'monthly: top of bracket 4 equals the base of bracket 5');
peso(toPesos(withholdingTax(toCentavos(666667), 'monthly', rates)), 183541.8,
  'monthly: top of bracket 5 equals the base of bracket 6');
peso(toPesos(withholdingTax(0, 'monthly', rates)), 0, 'monthly: zero taxable is zero tax');

peso(toPesos(withholdingTax(toCentavos(10417), 'semiMonthly', rates)), 0,
  'semi-monthly: exactly at the exempt ceiling');
peso(toPesos(withholdingTax(toCentavos(16667), 'semiMonthly', rates)), 937.5,
  'semi-monthly: top of bracket 2 equals the base of bracket 3');

throws(() => withholdingTax(1000, 'weekly', rates), 'unknown period throws');

/* ================================================================== */
section('Full payslip — hand-computed cases');

{
  const r = computePayroll({ gross: 25000 }, rates);
  peso(r.contributions.sss, 1250, '25,000 — SSS');
  peso(r.contributions.philhealth, 625, '25,000 — PhilHealth');
  peso(r.contributions.pagibig, 200, '25,000 — Pag-IBIG');
  peso(r.contributions.total, 2075, '25,000 — total contributions');
  peso(r.taxableIncome, 22925, '25,000 — taxable income');
  pesoPending(r.withholdingTax, 313.8, '25,000 — withholding tax');
  pesoPending(r.net, 22611.2, '25,000 — NET');
  peso(r.whereItWent, 2388.8, '25,000 — where it went');
  eq(r.deductionRate, 9.56, '25,000 — deduction rate %');
}

{
  const r = computePayroll({ gross: 15000 }, rates);
  peso(r.contributions.total, 1325, '15,000 — total contributions');
  peso(r.withholdingTax, 0, '15,000 — BELOW the tax threshold, tax is zero');
  peso(r.net, 13675, '15,000 — NET');
}

{
  const r = computePayroll({ gross: 50000 }, rates);
  peso(r.contributions.sss, 1750, '50,000 — SSS is capped');
  peso(r.contributions.philhealth, 1250, '50,000 — PhilHealth');
  peso(r.contributions.total, 3200, '50,000 — total contributions');
  peso(r.taxableIncome, 46800, '50,000 — taxable income');
  pesoPending(r.withholdingTax, 4568.4, '50,000 — withholding tax');
  pesoPending(r.net, 42231.6, '50,000 — NET');
}

{
  const r = computePayroll({ gross: 120000 }, rates);
  peso(r.contributions.sss, 1750, '120,000 — SSS capped');
  peso(r.contributions.philhealth, 2500, '120,000 — PhilHealth capped');
  peso(r.contributions.total, 4450, '120,000 — total contributions');
  peso(r.taxableIncome, 115550, '120,000 — taxable income');
  pesoPending(r.withholdingTax, 20762.55, '120,000 — withholding tax');
  pesoPending(r.net, 94787.45, '120,000 — NET');
}

{
  const r = computePayroll({ gross: 8000 }, rates);
  peso(r.contributions.philhealth, 250, '8,000 — PhilHealth uses the floor');
  peso(r.contributions.pagibig, 160, '8,000 — Pag-IBIG is 2% of 8,000');
  peso(r.contributions.total, 810, '8,000 — total contributions');
  peso(r.withholdingTax, 0, '8,000 — no tax');
  peso(r.net, 7190, '8,000 — NET');
}

/* ================================================================== */
section('Minimum wage earner — exempt from income tax');

{
  const plain = computePayroll({ gross: 18000 }, rates);
  const mwe = computePayroll({ gross: 18000, isMinimumWageEarner: true }, rates);
  peso(mwe.withholdingTax, 0, 'minimum wage earner pays no withholding tax');
  peso(mwe.contributions.total, plain.contributions.total,
    'minimum wage earner still pays contributions');
  eq(mwe.net >= plain.net, true, 'minimum wage earner nets at least as much');
}

/* ================================================================== */
section('Semi-monthly');

{
  const r = computePayroll({ gross: 12500, period: 'semiMonthly' }, rates);
  peso(r.contributions.sss, 625, 'semi-monthly — SSS is half the monthly share');
  peso(r.contributions.philhealth, 312.5, 'semi-monthly — PhilHealth is half');
  peso(r.contributions.pagibig, 100, 'semi-monthly — Pag-IBIG is half');
  peso(r.contributions.total, 1037.5, 'semi-monthly — total contributions');
  peso(r.taxableIncome, 11462.5, 'semi-monthly — taxable income');
  pesoPending(r.withholdingTax, 156.83, 'semi-monthly — withholding tax');
  pesoPending(r.net, 11305.67, 'semi-monthly — NET');

  // Worth knowing: the two filing frequencies do NOT agree to the centavo.
  const monthly = computePayroll({ gross: 25000 }, rates);
  const twiceSemi = Math.round(r.net * 2 * 100) / 100;
  eq(twiceSemi !== monthly.net, true,
    'semi-monthly x2 differs from monthly — a real, explainable rounding gap');
}

/* ================================================================== */
section('Non-taxable allowances');

{
  const base = computePayroll({ gross: 25000 }, rates);
  const withAllow = computePayroll({ gross: 25000, nonTaxableAllowances: 2500 }, rates);
  peso(withAllow.contributions.total, base.contributions.total,
    'allowances do not change contributions');
  peso(withAllow.withholdingTax, base.withholdingTax,
    'allowances within de minimis do not change tax');
  peso(withAllow.net, base.net + 2500, 'allowances land fully in take-home');
  peso(withAllow.gross, 27500, 'gross is all the cash: basic plus every allowance');
  peso(withAllow.basic, 25000, 'basic pay is reported separately');
}

/* ================================================================== */
section('Taxable allowances');

{
  const base = computePayroll({ basic: 25000 }, rates);
  const withTax = computePayroll({ basic: 25000, taxableAllowance: 3000 }, rates);

  peso(withTax.contributions.total, base.contributions.total,
    'a taxable allowance does not change contributions on the basic base');
  peso(withTax.taxableIncome, base.taxableIncome + 3000,
    'a taxable allowance raises taxable income peso for peso');
  ok(withTax.withholdingTax > base.withholdingTax,
    'a taxable allowance raises the tax');
  peso(withTax.net, withTax.gross - withTax.contributions.total - withTax.withholdingTax,
    'net still reconciles: gross less contributions less tax');

  // The point of the distinction, in one assertion.
  const nonTax = computePayroll({ basic: 25000, nonTaxableAllowance: 3000 }, rates);
  ok(nonTax.net > withTax.net,
    '₱3,000 non-taxable is worth more than ₱3,000 taxable');
  peso(nonTax.gross, withTax.gross, 'both show the same gross on the payslip');
}

/* ================================================================== */
section('Contribution base switch');

{
  const onBasic = computePayroll({ basic: 15000, taxableAllowance: 5000 }, rates);
  const onBoth = computePayroll(
    { basic: 15000, taxableAllowance: 5000, contributionBase: 'withTaxableAllowance' }, rates);

  ok(onBoth.contributions.total > onBasic.contributions.total,
    'including the allowance in the base raises the contributions');
  peso(onBoth.gross, onBasic.gross, 'the base switch never changes gross');
  ok(onBoth.net < onBasic.net,
    'a higher contribution base lowers take-home');
  eq(onBasic.meta.contributionBaseAmount, 15000, 'the base used is reported');
  eq(onBoth.meta.contributionBaseAmount, 20000, 'the wider base is reported too');
}

/* ================================================================== */
section('Allowance warnings');

{
  const r = computePayroll({ basic: 25000, nonTaxableAllowance: 2000, taxableAllowance: 1000 }, rates);
  ok(r.warnings.some(w => w.code === 'allowance_assumptions'),
    'a non-taxable allowance surfaces the de minimis ceiling assumption');
  ok(r.warnings.some(w => w.code === 'contribution_base'),
    'a taxable allowance surfaces which base the contributions used');

  const plain = computePayroll({ basic: 25000 }, rates);
  ok(plain.warnings.length === 0,
    'no allowances, no allowance warnings — silence is the default');
}

/* ================================================================== */
section('Reverse — what gross do I need for this net?');

{
  const target = 22611.2;
  const r = grossFromNet(target, {}, rates);
  peso(r.gross, 25000, 'reverse: 22,611.20 net implies 25,000 gross');
  eq(r.net >= target, true, 'reverse: result nets at least the target');
}

{
  const r = grossFromNet(30000, {}, rates);
  eq(r.net >= 30000, true, 'reverse: 30,000 target is met or exceeded');
  const oneLess = computePayroll({ gross: r.gross - 0.01 }, rates);
  eq(oneLess.net < 30000, true, 'reverse: one centavo less falls short — the answer is minimal');
}

/* ================================================================== */
section('Compare two offers');

{
  const c = compare({ gross: 25000 }, { gross: 28000 }, rates);
  peso(c.grossDifference, 3000, 'compare: gross difference');
  eq(c.netDifference < 3000, true,
    'compare: the net gap is SMALLER than the gross gap — the point of the feature');
  eq(c.netDifference > 0, true, 'compare: the higher offer still nets more');
}

/* ================================================================== */
section('Guards');

throws(() => computePayroll({ gross: -1 }, rates), 'negative gross throws');
throws(() => computePayroll({ gross: 'abc' }, rates), 'non-numeric gross throws');
throws(() => computePayroll({ gross: 25000, period: 'weekly' }, rates), 'unsupported period throws');
eq(computePayroll({ gross: 0 }, rates).net, 0,
  'zero gross nets zero — the floors must NOT apply to a non-earner');
eq(computePayroll({ gross: 0 }, rates).contributions.total, 0, 'zero gross pays no contributions');
eq(computePayroll({ gross: 0 }, rates).deductionRate, 0, 'zero gross does not divide by zero');

/* ================================================================== */
section('Warnings — the floors must be surfaced, never silent');

{
  const r = computePayroll({ gross: 25000 }, rates);
  eq(r.warnings.length, 0, 'a normal salary produces no warnings');
}

{
  const r = computePayroll({ gross: 8000 }, rates);
  eq(r.warnings.some(w => w.code === 'philhealth_floor'), true,
    '8,000 warns that PhilHealth used the floor');
  eq(r.warnings.some(w => w.code === 'sss_floor'), false,
    '8,000 is above the SSS floor, so no SSS warning');
}

{
  const r = computePayroll({ gross: 1400 }, rates);
  eq(r.warnings.some(w => w.code === 'philhealth_floor'), true, '1,400 warns on PhilHealth floor');
  eq(r.warnings.some(w => w.code === 'sss_floor'), true, '1,400 warns on SSS floor');
  peso(r.contributions.pagibig, 14, '1,400 uses the Pag-IBIG 1% tier');
  eq(r.net > 0, true, '1,400 still nets something positive');
}

{
  const r = computePayroll({ gross: 400 }, rates);
  eq(r.warnings.some(w => w.code === 'deductions_exceed_gross'), true,
    '400 gross: deductions exceed pay and the app says so rather than showing a negative');
}

/* ================================================================== */

const total = passed + failed;
process.stdout.write('\n' + '-'.repeat(60) + '\n');
if (failed) {
  process.stdout.write(`\n  ${failed} FAILED\n\n`);
  for (const f of failures) process.stdout.write(`  ✗ ${f}\n\n`);
}
process.stdout.write(`  ${passed}/${total} assertions passed\n`);
process.stdout.write(`  rates effective ${rates.effective}\n`);

const unverified = Object.entries(rates)
  .filter(([, v]) => v && typeof v === 'object' && v.verify === false)
  .map(([k]) => k);

if (unverified.length) {
  process.stdout.write(
    `\n  ⚠  ${unverified.length} rate groups are NOT verified against a primary source:\n` +
    `     ${unverified.join(', ')}\n`
  );
}
if (pendingVerify) {
  process.stdout.write(
    `  ⚠  ${pendingVerify} expected values need a hand-check against a real payslip\n`
  );
}
process.stdout.write('\n');

process.exit(failed ? 1 : 0);
